Version: 0.0.3
VestRecoil: 0
OffhandRecoilStrength: 0.7
VestClimbEffects: false
Clapping: false
HighFive: true
ShowHighFiveRegion: false
ShowLoadedEffects: false
FoodEatIntensity: 1
SodaBubbleIntensity: 1
FallEffect:
  EffectVariants: 10
  MaxConcurrentEffectCount: 6
  StrengthTarget: 40
  SpeedTarget: 15
  ConcurrentTarget: 30
  StrengthMultiplier: 1
Effects:
  Flying:
    Modifiers:
      FromFalling:
        BaselineTime: 0.200000003
        ProgressMultiplier: 0.699999988
      HighFlight:
        MinDistance: 20
        BaselineTime: 0.300000012
        ProgressMultiplier: 0.5
    Front:
      Strength:
        Multiplier: 0.400000006
        Goal:
          Start: 0.300000012
          End: 1
        Target: 0.75
      Speed:
        Goal:
          Start: 1
          End: 0.5
        Target: 0.75
      EffectPool:
        Variants: 8
        MaxConcurrency: 4
        Target: 2
      Enabled: true
    Back:
      Strength:
        Multiplier: 0.400000006
        Goal:
          Start: 0.300000012
          End: 1
        Target: 0.75
      Speed:
        Goal:
          Start: 1
          End: 0.5
        Target: 0.75
      EffectPool:
        Variants: 8
        MaxConcurrency: 4
        Target: 2
      Enabled: true
    Arms:
      Strength: 0.5
      Target: 0.75
      Enabled: true
    Enabled: true
